### ISSUE TITLE
Does not work for not application related commands

### ISSUE THREAD

**Issue by jvenezia** [Bastes/hrk#15]
````
$ hrk login
Error: No remote has been previously defined and the command does not explicitely mention a remote
```

````
$ heroku login
Enter your Heroku credentials.
Email: 
```

**Comment by Bastes** [comment]
Why use hrk for a command that doesn't require a remote though?

**Comment by jvenezia** [comment]
I wanted to always use hrk, for more convenience. Indeed, I end up using both 'heroku' and 'hrk' and it's ok for me.

**Comment by Bastes** [comment]
Well. I'll keep it under "advice".
