### ISSUE TITLE
Suggestion - Confirmation prompt when no app name is given

### ISSUE THREAD

**Issue by jvenezia** [Bastes/hrk#8]
Confirmation prompt when no app name is given, to avoid doing mistakes in production environment.

Exemple : 
The first time : 
```
$ hrk run rake db:migrate -a production
```

The second time : 
```
$ hrk run rake db:migrate
The command "run rake db:migrate" will be executed in "production" application.
Press "Enter" to confirm.
```

**Comment by Bastes** [comment]
No .hrkrc yet, but the wait for 5 seconds then ask for confirmation thing is out. Planning on adding the .hrk config file soon, when I've got a little time to think about how to make it work and which params to add first.
